from pages.login import LoginPage
from pages.register import RegisterPage
from pages.tasks import TasksPage
from pages.pomodoro import PomodorosPage
from pages.converter import ConverterPage
from pages.dictionary import DictionaryPage
from pages.translator import TranslatorPage
from pages.ai_answer import AIPage
from pages.home import HomePage
